# 指定构建环境是Node.js，当前版本是稳定版
anguage: node_js
node_js: stable

# 设置缓存文件
cache:
  directories:
    - node_modules

#在构建之前安装hexo环境和主题，这里的主题就是原来修改过的主题，我将其托管到另一个github仓库，直接clone就行，否则每次都是新的主题，要重新设置。
before_install:
  - npm install -g hexo-cli
  - npm install -g gulp

#安装git插件和搜索功能插件
install:
  - npm install

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo g && gulp

# 设置git提交名，邮箱；最后depoy部署
after_script:
  - git config user.name "Yangkai.Shen"
  - git config user.email "237497819@qq.com"
  - hexo deploy