anguage: node_js
node_js: stable
cache:
  directories:
  - node_modules
before_install:
  - npm install -g hexo-cli
  - npm install -g gulp
install:
  - npm install
script:
  - hexo clean
  - hexo g && gulp
after_script:
  - cd ./public
  - git init
  - git config user.name "Yangkai.Shen"
  - git config user.email "237497819@qq.com"
  - git add .
  - git commit -m "TravisCI 自动部署"
  # Github Pages
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GITHUB_PAGE}" master:master 
  # Coding Pages
  - git push --force --quiet "https://xkcoding:${CODING_TOKEN}@${CODING_PAGE}" master:master
env:
  global:
    - GITHUB_PAGE: github.com/xkcoding/xkcoding.github.io.git
    - CODING_PAGE: git.coding.net/xkcoding/xkcoding.git,master